apiVersion: apps/v1
kind: Deployment
metadata:
  name: localchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localchat
  template:
    metadata:
      labels:
        app: localchat
    spec:
      containers:
      - name: localchat
        image: localchat:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_CLIENT_ID
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_TENANT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_CLIENT_SECRET
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"