name: Build and deploy Dockerized ASP.NET Core app to Azure Web App - localchat

on:
  push:
    branches:
      - release/v1
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Grant id-token write permission for OIDC
      contents: read  # Required for actions/checkout
    env:
      FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN_PRODUCTION }} # Dynamically set from secrets

    steps:
      # Checkout code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace CORS Origin in Code
        run: |
          echo "Replacing origin URL in CORS configuration..."
          sed -i 's#http://localhost:5173#'${FRONTEND_ORIGIN}'#g' ./LocalChat/Program.cs


      # Log in to Docker Hub or Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name localchat

      # Build and push the Docker image to Azure Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -f ./LocalChat/Dockerfile -t localchat.azurecr.io/localchat:latest .
          docker push localchat.azurecr.io/localchat:latest

  deploy_to_azure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Grant id-token write permission for OIDC
      contents: read  # Required for actions/checkout
    needs: build_and_push_docker_image
    steps:
      # Login to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'SERVICE_PRINCIPAL'

      # Deploy the image from Azure Container Registry to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'localchat' # Replace with your Azure Web App name
          images: localchat.azurecr.io/localchat:latest
